package com.focal.ui.theme

import androidx.compose.ui.graphics.Color

// M3 palette generated from seed #C8956C (Focal warm gold)

// Light scheme
val md_theme_light_primary = Color(0xFF8B5E3C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDB8)
val md_theme_light_onPrimaryContainer = Color(0xFF311A00)
val md_theme_light_secondary = Color(0xFF6E5D4B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF9DFC8)
val md_theme_light_onSecondaryContainer = Color(0xFF271A0D)
val md_theme_light_tertiary = Color(0xFF5E6237)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE2E7B1)
val md_theme_light_onTertiaryContainer = Color(0xFF1B1E00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFF8F4)
val md_theme_light_onBackground = Color(0xFF201A14)
val md_theme_light_surface = Color(0xFFFFF8F4)
val md_theme_light_onSurface = Color(0xFF201A14)
val md_theme_light_surfaceVariant = Color(0xFFF1DFD0)
val md_theme_light_onSurfaceVariant = Color(0xFF504539)
val md_theme_light_outline = Color(0xFF837468)
val md_theme_light_outlineVariant = Color(0xFFD4C4B5)
val md_theme_light_inverseSurface = Color(0xFF362F28)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEE3)
val md_theme_light_inversePrimary = Color(0xFFF5BB84)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFFFF1E7)
val md_theme_light_surfaceContainer = Color(0xFFF5EDE6)
val md_theme_light_surfaceContainerHigh = Color(0xFFEFE8E0)
val md_theme_light_surfaceContainerHighest = Color(0xFFE9E2DA)

// Dark scheme
val md_theme_dark_primary = Color(0xFFF5BB84)
val md_theme_dark_onPrimary = Color(0xFF4A2800)
val md_theme_dark_primaryContainer = Color(0xFF6D4422)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB8)
val md_theme_dark_secondary = Color(0xFFDCC3AD)
val md_theme_dark_onSecondary = Color(0xFF3D2E20)
val md_theme_dark_secondaryContainer = Color(0xFF554535)
val md_theme_dark_onSecondaryContainer = Color(0xFFF9DFC8)
val md_theme_dark_tertiary = Color(0xFFC7CB97)
val md_theme_dark_onTertiary = Color(0xFF30330D)
val md_theme_dark_tertiaryContainer = Color(0xFF464A22)
val md_theme_dark_onTertiaryContainer = Color(0xFFE2E7B1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF17120D)
val md_theme_dark_onBackground = Color(0xFFEDE0D5)
val md_theme_dark_surface = Color(0xFF17120D)
val md_theme_dark_onSurface = Color(0xFFEDE0D5)
val md_theme_dark_surfaceVariant = Color(0xFF504539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C4B5)
val md_theme_dark_outline = Color(0xFF9D8F81)
val md_theme_dark_outlineVariant = Color(0xFF504539)
val md_theme_dark_inverseSurface = Color(0xFFEDE0D5)
val md_theme_dark_inverseOnSurface = Color(0xFF362F28)
val md_theme_dark_inversePrimary = Color(0xFF8B5E3C)
val md_theme_dark_surfaceContainerLowest = Color(0xFF120D08)
val md_theme_dark_surfaceContainerLow = Color(0xFF201A14)
val md_theme_dark_surfaceContainer = Color(0xFF241E18)
val md_theme_dark_surfaceContainerHigh = Color(0xFF2F2922)
val md_theme_dark_surfaceContainerHighest = Color(0xFF3A342D)
